openapi: 3.0.3
info:
  title: Pics
  version: 1.0.0
  description: Pics REST API
paths:
  /api/v1/images/:
    get:
      operationId: images_list
      tags:
      - images
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ImageList'
          description: ''
  /api/v1/images/expiring-link/:
    get:
      operationId: images_expiring_link_list
      tags:
      - images
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExpiringLinkList'
          description: ''
    post:
      operationId: images_expiring_link_create
      tags:
      - images
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExpiringLinkCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ExpiringLinkCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ExpiringLinkCreate'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpiringLinkCreate'
          description: ''
  /api/v1/images/expiring-link/{signed_link}/:
    get:
      operationId: images_expiring_link_retrieve
      parameters:
      - in: path
        name: signed_link
        schema:
          type: string
        required: true
      tags:
      - images
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
  /api/v1/images/upload/:
    post:
      operationId: images_upload_create
      tags:
      - images
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImageCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ImageCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ImageCreate'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageCreate'
          description: ''
  /api/v1/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    ExpiringLinkCreate:
      type: object
      properties:
        image:
          type: string
          format: uuid
        time_to_expired:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
      required:
      - image
      - time_to_expired
    ExpiringLinkList:
      type: object
      properties:
        link:
          type: string
          maxLength: 255
      required:
      - link
    ImageCreate:
      type: object
      properties:
        image:
          type: string
          format: uri
      required:
      - image
    ImageList:
      type: object
      properties:
        images:
          type: array
          items: {}
      required:
      - images
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
